name: quicktask
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.3
dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.2
 
  flutter_riverpod: ^2.4.9
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  equatable: ^2.0.7
  get_it: ^9.2.0
  uuid: ^4.5.2
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  http: ^1.6.0
  flutter_dotenv: ^6.0.0
  # flutter_native_timezone: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.2

  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  riverpod_generator: ^2.4.0
    


flutter:
  uses-material-design: true
  assets:
    - .env
 
