name: quicktask
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.3
dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.2
 
  flutter_riverpod: ^2.4.9
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  equatable: ^2.0.7
  get_it: ^9.2.0
  uuid: ^4.5.2

dev_dependencies:
  build_runner: ^2.4.2

  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  riverpod_generator: ^2.4.0
  # build_resolvers: ^2.5.2
  dart_style: ^2.3.3
# dependencies:
#   flutter:
#     sdk: flutter
#   flutter_riverpod: ^3.0.3
#   get_it: ^9.2.0
#   hive: ^2.2.3
#   hive_flutter: ^1.1.0
#   uuid: ^4.5.1
#   riverpod_annotation: ^3.0.3

# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   flutter_lints: ^6.0.0
#   build_runner: ^2.4.6
#   riverpod_generator: ^3.0.3


flutter:
  uses-material-design: true
